image: Visual Studio 2017

matrix:
  fast_finish: false

platform:
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" .

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

test_script:
  - ctest --output-on-failure
